#生产环境
#端口
server:
  port: 5001


#mysq;
spring:
  homeUrl:
  images:
    filePath: /usr/local/uploadImage/
  application:
    name: xinwen-web-body #指定服务名
  datasource:
    url: jdbc:mysql://47.119.158.164:3377/xinwen?useUnicode=true&characterEncoding=utf8
    username: root
    password: Zhuang$2015
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 154.92.18.217
#    port: 6379
#    password: jiehuihui520
#下面代码注册到nacos里面
#  cloud:
#    nacos:
#      discovery:
#        ###服务注册Nacos地址
#        server-addr: 127.0.0.1:8848


caching:
  specs:
    article:
      # 单位（秒）
      timeout: 3600
      expireMode: 0


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:6868/eureka  #注册中心服务地址
#  instance:
#    prefer-ip-address: true  #注册中心以ip地址形式注册

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml


#配置redis

#日志
#logging.file=ec.log
#logging:
#  config: classpath:logback.xml