#开发环境
#端口
server:
  port: 5001

#mysq;
spring:
  datasource:
    url: jdbc:mysql://192.168.10.111:3306/zjl?useUnicode=true&characterEncoding=UTF-8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.1.103
#    port: 6379
#    password: 123456
  #热部署文件，页面不产生缓存，及时更新
  thymeleaf:
    cache: false


#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置redis

#日志
#logging.file=ec.log
#logging:
#  config: classpath:logback.xml

